version: '3.8'

services:
  twenty-mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - TWENTY_API_URL=${TWENTY_API_URL}
      - TWENTY_API_KEY=${TWENTY_API_KEY}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - CACHE_ENABLED=${CACHE_ENABLED:-true}
      - CACHE_TTL_SECONDS=${CACHE_TTL_SECONDS:-300}
      - MAX_CONCURRENT_REQUESTS=${MAX_CONCURRENT_REQUESTS:-10}
      - REQUEST_TIMEOUT_MS=${REQUEST_TIMEOUT_MS:-10000}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "process.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - ./logs:/app/logs:rw
    networks:
      - twenty-mcp-network

networks:
  twenty-mcp-network:
    driver: bridge